### PR TITLE
Made a simple Announcement form in teacher announcement page.

### PR DESCRIPTION
**Pull request by sophiaquach16**

### CODE REVIEW

**Comment by sophiaquach16** [comment]
#122

**Comment by Helen2hang** [comment]
hey @sophiaquach16 my pull request had to be merged before your could put the html form in. The html form should go inside the page teacherCreateQuiz.php file.

**Comment by sophiaquach16** [comment]
@Helen2hang done!

**Comment by Helen2hang** [comment]
hey sophia the slash for br goes after br not before. So you have to change the < / br> to <br / >.

**Comment by sophiaquach16** [comment]
@Helen2hang just fixed the <br/>

**Comment by Helen2hang** [comment]
@sophiaquach16 the TA doesn't want us to use the word "update" in our commits. Can you try to change your commit message? https://help.github.com/articles/changing-a-commit-message/

**Pull request closed without merging**
