### PR TITLE
White divs of student&teacher dashboard for a course

### PR DESCRIPTION
**Pull request by Helen2hang**
- Positioned the divs
- Made them resize-able.
- Added white background color
Task #140 
User Story #124 & #139

The rest is up to Orel and Robert.

### CODE REVIEW

**Comment by Helen2hang** [comment]
This is what the teacher/student sees after they click on the course.
coursedashboard

**Comment by z-alex** [comment]
I think you forgot to remove the line "<link rel="stylesheet" href="css/style2.css" />" since we don't have that file in the project.

**Comment by Helen2hang** [comment]
Oops yeah I forgot to remove that line. I tried testing something because the css didn't work properly at first. But it was the problem of my browser!

**Comment by Helen2hang** [comment]
Ok I removed the line that @z-alex has mentionned.

**Comment by z-alex** [comment]
Alright

**Pull request merged**
